#!/usr/bin/env python
import sys
import logging

from editor import Editor

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s', datefmt='', stream=sys.stderr)

if __name__ == '__main__':
	try:
		Editor.main()
	except (EOFError, KeyboardInterrupt):
		print
		sys.exit(1)
